#!/usr/bin/env bash
# Maestro — launcher local standalone
#
# Sobe o backend FastAPI/Uvicorn direto, usando o venv já criado em app/env/.
#
# O launcher é "version-aware" (padrão herdado do Directo start.sh): antes de
# subir um backend novo, prova a porta. Se já houver um Maestro respondendo,
# compara a versão reportada por /health/version com a versão declarada no
# arquivo VERSION na raiz do repo. Se bater, reusa. Se diferir (ou o holder
# não responder versão), mata e sobe fresh. Se a porta estiver ocupada por
# um processo que não responde ao probe (ex: outro app), falha com
# mensagem específica em vez de subir e dar bind error.
#
# Uso:
#   ./start_local.sh                  # porta padrão 7860, log em .launcher.log
#   ./start_local.sh --port 7865      # porta custom
#   ./start_local.sh --compile        # passa --compile para launch.py (kernel fusion)
#   ./start_local.sh --share          # liga 0.0.0.0 (LAN) em vez de 127.0.0.1
#   ./start_local.sh --no-build       # pula verificação de UI build
#   ./start_local.sh --no-open        # não abre o navegador automaticamente
#   ./start_local.sh --force          # ignora detecção de stale build; sempre reinicia

set -euo pipefail

# Resolve diretório do script (funciona com symlinks)
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
APP_DIR="$SCRIPT_DIR/app"
PIDFILE="$APP_DIR/.launcher.pid"
LOGFILE="$APP_DIR/.launcher.log"
VERSION_FILE="$SCRIPT_DIR/VERSION"

# Defaults
PORT="7860"
COMPILE_FLAG=""
BIND_HOST="127.0.0.1"
SKIP_BUILD=0
FORCE_RESTART=0
AUTO_OPEN=1   # open the browser on the default handler unless --no-open

# Parse args
while [[ $# -gt 0 ]]; do
  case "$1" in
    --port|-p)
      if [[ $# -lt 2 || ! "$2" =~ ^[0-9]{1,5}$ ]]; then
        echo "[start_local] ERRO: --port requer um número entre 1 e 65535" >&2
        exit 2
      fi
      PORT=$((10#$2))
      if (( PORT < 1 || PORT > 65535 )); then
        echo "[start_local] ERRO: porta deve estar entre 1 e 65535" >&2
        exit 2
      fi
      shift 2 ;;
    --compile)     COMPILE_FLAG="--compile"; shift ;;
    --share)       BIND_HOST="0.0.0.0"; shift ;;
    --no-build)    SKIP_BUILD=1; shift ;;
    --force)       FORCE_RESTART=1; shift ;;
    --no-open)     AUTO_OPEN=0; shift ;;
    -h|--help)
      sed -n '2,12p' "$0" | sed 's/^# \{0,1\}//'
      echo "  --force             ignora stale build; sempre reinicia" >&2
      echo "  --no-open           não abre o navegador automaticamente" >&2
      exit 0 ;;
    *)
      echo "Argumento desconhecido: $1" >&2
      exit 2 ;;
  esac
done

# Declared Maestro version (from VERSION file). If missing, fall back to
# "0.0.0+unknown" so the comparison still works (any running build that
# reports a real version will look "newer" than unknown and force restart).
EXPECTED_VERSION="0.0.0+unknown"
if [[ -f "$VERSION_FILE" ]]; then
  EXPECTED_VERSION="$(tr -d '[:space:]' < "$VERSION_FILE")"
  [[ -z "$EXPECTED_VERSION" ]] && EXPECTED_VERSION="0.0.0+unknown"
fi

echo "[start_local] Maestro launcher (standalone) — porta $PORT ($BIND_HOST); versão esperada: $EXPECTED_VERSION"

# --- 1. Detect venv ---
VENV=""
for candidate in env-sol env-rtx50 env; do
  if [[ -x "$APP_DIR/$candidate/bin/python" ]]; then
    VENV="$candidate"
    break
  fi
done

if [[ -z "$VENV" ]]; then
  echo "[start_local] ERRO: nenhum venv encontrado em app/env{,-sol,-rtx50}/" >&2
  echo "             Crie o ambiente Python conforme README.md:" >&2
  exit 1
fi
PY="$APP_DIR/$VENV/bin/python"
echo "[start_local] Usando venv: $VENV ($PY)"

# --- 2. Sanity: GPU detectável ---
if command -v nvidia-smi >/dev/null 2>&1; then
  GPU_NAME=$(nvidia-smi --query-gpu=name --format=csv,noheader 2>/dev/null | head -1 || true)
  GPU_DRIVER=$(nvidia-smi --query-gpu=driver_version --format=csv,noheader 2>/dev/null | head -1 || true)
  echo "[start_local] GPU: ${GPU_NAME:-desconhecida} (driver ${GPU_DRIVER:-?})"
else
  echo "[start_local] AVISO: nvidia-smi não encontrado — verifique o driver NVIDIA antes de gerar mídia"
fi

# --- 3. Sanity: UI buildada ---
if [[ "$SKIP_BUILD" -eq 0 ]]; then
  if [[ ! -f "$SCRIPT_DIR/ui/dist/index.html" ]]; then
    echo "[start_local] UI não buildada — correndo npm install + npm run build..."
    if [[ ! -d "$SCRIPT_DIR/ui/node_modules" ]]; then
      (cd "$SCRIPT_DIR/ui" && npm install) || {
        echo "[start_local] ERRO: npm install falhou" >&2
        exit 3
      }
    fi
    # Write the backend port into ui/.env.local so vite's dev-proxy
    # AND the production build both point at the right port. Without
    # this the proxy hits 127.0.0.1:7860 even when launch.py had to
    # fall forward to a free port (e.g. 7861) because something else
    # was holding 7860. .env.local is gitignored; we overwrite it on
    # every launch so a stale value never leaks across restarts.
    UI_ENV="$SCRIPT_DIR/ui/.env.local"
    cat > "$UI_ENV" <<EOF
# Generated by start_local.sh — do not edit by hand. The Vite proxy
# in vite.config.ts reads MAESTRO_BACKEND_PORT to forward /api calls
# to the actual bind. Regenerated on every launcher invocation.
MAESTRO_BACKEND_PORT=${PORT}
EOF
    echo "[start_local] wrote $UI_ENV (MAESTRO_BACKEND_PORT=${PORT})"
    (cd "$SCRIPT_DIR/ui" && MAESTRO_BACKEND_PORT="$PORT" npm run build) || {
      echo "[start_local] ERRO: UI build falhou" >&2
      exit 3
    }
  else
    echo "[start_local] UI dist já existe — ok"
  fi
fi

# --- 3.5. fix_llama_symlinks (idempotente, < 50ms) ---
#
# O bundle de llama.cpp em app/ckpts/llm/bin/ vem sem os SONAME
# symlinks (libllama-common.so.0 etc.) que o ld.so procura. Sem eles
# o llama-server child process morre com "code 127" e o Director
# perde o caminho de LLM (Gemma 4) — sintoma silencioso, hard to
# spot. O script fix_llama_symlinks.sh cria os symlinks faltantes
# e é seguro rodar todo startup (cria só o que falta).
if [[ -x "$APP_DIR/scripts/fix_llama_symlinks.sh" ]]; then
  "$APP_DIR/scripts/fix_llama_symlinks.sh" || echo "[start_local] AVISO: fix_llama_symlinks falhou (não fatal — backend sobe sem LLM advisor)" >&2
fi

# --- 4. ensure_service (version-aware, padrão Directo) ---
#
# Antes de qualquer decisão sobre "subir novo backend", prova quem está na
# porta. Três casos:
#   A) Porta livre → segue direto para §6.
#   B) Porta ocupada por Maestro respondendo, mesma versão → reusa e sai.
#      (mensagem "(skipped) — already running vX.Y.Z").
#   C) Porta ocupada por Maestro com versão diferente (ou holder não-Maestro)
#      → mata holder e segue para §6. Salvo se --force foi passado, então
#      já pulamos para §6 sem tentar reusar.
#   D) Porta ocupada por processo que não responde → ERRO fail-fast.

probe_url="http://127.0.0.1:${PORT}/"
version_url="http://127.0.0.1:${PORT}/health/version"

probe_running_version() {
  # Returns the version string reported by /health/version, or empty
  # string if unreachable / not Maestro / not JSON. Uses python3 (not
  # python) to be predictable across distros — some systems have only
  # python3 on PATH; some have a python shim without the json module.
  local body
  body=$(curl --noproxy '*' --fail -sS --max-time 2 "$version_url" 2>/dev/null || true)
  if [[ -z "$body" ]]; then
    return 0
  fi
  python3 -c 'import json,sys; print(json.load(sys.stdin).get("version",""))' <<<"$body" 2>/dev/null || true
}

probe_index_alive() {
  # Lightweight index probe — returns 0 if a Maestro (any version) is up.
  curl --noproxy '*' --fail -sS -o /dev/null --max-time 1 "$probe_url" 2>/dev/null
}

if [[ "$FORCE_RESTART" -eq 1 ]]; then
  echo "[start_local] --force ativo; pulando probe e indo matar holder da porta"
else
  if probe_index_alive; then
    RUNNING_VERSION="$(probe_running_version || true)"
    if [[ -n "$RUNNING_VERSION" && "$RUNNING_VERSION" == "$EXPECTED_VERSION" ]]; then
      echo "[start_local] (skipped) — Maestro v${RUNNING_VERSION} já está rodando na porta ${PORT}"
      echo "[start_local] Para reiniciar: ./start_local.sh --force"
      echo "[start_local] Para parar: ./stop_local.sh"
      exit 0
    fi
    if [[ -n "$RUNNING_VERSION" ]]; then
      echo "[start_local] Stale build detectado: porta ${PORT} tem Maestro v${RUNNING_VERSION}, esperado v${EXPECTED_VERSION}"
    else
      echo "[start_local] Holder na porta ${PORT} não responde /health/version; tratando como stale"
    fi
    # Stale → cair no kill abaixo.
  fi
fi

# --- 5. Mata holder da porta (se houver) ---
kill_holder_of_port() {
  if command -v ss >/dev/null 2>&1; then
    local holder
    holder=$(ss -ltnp 2>/dev/null | awk -v p=":$PORT" '$4 ~ p {print $0}' | grep -oP 'pid=\K[0-9]+' | head -1 || true)
    if [[ -n "${holder:-}" ]]; then
      echo "[start_local] Porta $PORT ocupada por PID $holder — matando"
      kill "$holder" 2>/dev/null || true
      sleep 2
      kill -9 "$holder" 2>/dev/null || true
      return 0
    fi
  fi
  return 1
}

# Se pidfile existe e está vivo, mata. Senão tenta detectar holder via ss.
if [[ -f "$PIDFILE" ]]; then
  OLD_PID=$(cat "$PIDFILE" 2>/dev/null || true)
  if [[ -n "${OLD_PID:-}" ]] && kill -0 "$OLD_PID" 2>/dev/null; then
    echo "[start_local] PID antigo $OLD_PID ainda vivo — matando"
    kill "$OLD_PID" 2>/dev/null || true
    sleep 2
    kill -9 "$OLD_PID" 2>/dev/null || true
  fi
  rm -f "$PIDFILE"
else
  kill_holder_of_port || true
fi

# Fail-fast: se ainda houver holder sobrevivente que não responde ao probe,
# abortar antes de subir (evita bind error e mensagem confusa depois).
if probe_index_alive; then
  echo "[start_local] ERRO: porta ${PORT} ainda ocupada por processo que não conseguimos matar." >&2
  echo "             Verifique com: ss -ltnp 'sport = :${PORT}'" >&2
  exit 6
fi

# --- 6. Sobe o backend ---
cd "$APP_DIR"
echo "[start_local] Lançando backend → log: $LOGFILE"
SERVER_NAME="$BIND_HOST" SERVER_PORT="$PORT" \
  nohup "$PY" launch.py $COMPILE_FLAG >"$LOGFILE" 2>&1 &
BACKEND_PID=$!
echo "$BACKEND_PID" > "$PIDFILE"

echo "[start_local] Backend PID: $BACKEND_PID"

# --- 7. Espera o bind aparecer ---
URL="http://127.0.0.1:${PORT}/"
echo -n "[start_local] Aguardando bind em ${BIND_HOST}:${PORT} "
WAITED=0
MAX_WAIT=120
# launch.py falls forward to the next free port when the preferred
# one is taken (and prints "Port N was busy — using M instead.").
# The UI build embeds the preferred port in MAESTRO_BACKEND_PORT; if
# the actual bind landed elsewhere, we still want to point the user
# at the real URL, AND rewrite ui/.env.local so a future rebuild
# (e.g. after editing a component) doesn't lock in a stale target.
ACTUAL_PORT="$PORT"
while (( WAITED < MAX_WAIT )); do
  if ! kill -0 "$BACKEND_PID" 2>/dev/null; then
    echo ""
    echo "[start_local] ERRO: backend morreu logo após o start. Últimas linhas do log:" >&2
    tail -40 "$LOGFILE" >&2
    rm -f "$PIDFILE"
    exit 4
  fi
  if curl --noproxy '*' --fail -sS -o /dev/null --max-time 1 "$URL" 2>/dev/null; then
    echo " OK (após ${WAITED}s)"
    break
  fi
  # Detect auto-fallback from the backend's own log so we can update
  # URL + .env.local to the real port before the user clicks anything.
  fallback_match=$(grep -oE 'Port [0-9]+ was busy — using [0-9]+ instead' "$LOGFILE" 2>/dev/null | tail -1 || true)
  if [[ -n "$fallback_match" ]]; then
    detected=$(awk '{print $NF}' <<<"$fallback_match")
    if [[ -n "$detected" && "$detected" != "$PORT" ]]; then
      ACTUAL_PORT="$detected"
      URL="http://127.0.0.1:${ACTUAL_PORT}/"
      # Realign the UI's backend port so the next `npm run build`
      # (or vite dev) targets the real bind, not the preferred one.
      UI_ENV="$SCRIPT_DIR/ui/.env.local"
      cat > "$UI_ENV" <<EOF
# Generated by start_local.sh — do not edit by hand. The Vite proxy
# in vite.config.ts reads MAESTRO_BACKEND_PORT to forward /api calls
# to the actual bind. Regenerated on every launcher invocation.
MAESTRO_BACKEND_PORT=${ACTUAL_PORT}
EOF
    fi
  fi
  echo -n "."
  sleep 1
  WAITED=$(( WAITED + 1 ))
done

if (( WAITED >= MAX_WAIT )); then
  echo ""
  echo "[start_local] ERRO: backend não respondeu em ${MAX_WAIT}s. Tail do log:" >&2
  tail -40 "$LOGFILE" >&2
  echo "[start_local] PID $BACKEND_PID ainda vivo — matando" >&2
  kill "$BACKEND_PID" 2>/dev/null || true
  rm -f "$PIDFILE"
  exit 5
fi

# If the launcher detected an auto-fallback AND the UI was already
# built (we skipped step §3), the embedded proxy target still points
# at the preferred port — a one-time warning surfaces the mismatch
# instead of leaving the user to debug "API calls return 404".
if [[ "$ACTUAL_PORT" != "$PORT" && -f "$SCRIPT_DIR/ui/dist/index.html" ]]; then
  echo ""
  echo "[start_local] AVISO: backend está em $ACTUAL_PORT mas o UI build"
  echo "[start_local]         embute proxy para $PORT. Para alinhar: rode"
  echo "[start_local]         ./start_local.sh --no-build OU apague ui/dist/."
fi

# --- 8. Resumo ---
echo ""
echo "============================================================"
echo "  Maestro está rodando! (v${EXPECTED_VERSION})"
echo ""
echo "  UI (React):  $URL"
echo "  API docs:    ${URL}docs"
echo "  Health:      ${URL}health/version"
echo ""
echo "  PID:   $BACKEND_PID  (pidfile: $PIDFILE)"
echo "  Log:   $LOGFILE"
echo ""
echo "  Pare com:  ./stop_local.sh"
echo "  Acompanhe: tail -f $LOGFILE"
echo "============================================================"

# --- 9. Auto-open the browser (opt-out via --no-open) ---
#
# Launches the system default browser pointed at the local UI. We only
# do this when:
#   - AUTO_OPEN is still 1 (user didn't pass --no-open)
#   - the bind host is loopback (127.0.0.1 / localhost) — opening a
#     remote URL when --share binds 0.0.0.0 would surprise the operator
#     by pointing their browser at the LAN IP they may not want to use.
#   - we have a TTY-ish session OR the platform's `open` command is
#     available — under `nohup` from a cron job we shouldn't try.
#
# Failure is non-fatal: if no opener is found, just print a hint.
if (( AUTO_OPEN == 1 )) && [[ "$BIND_HOST" == "127.0.0.1" || "$BIND_HOST" == "localhost" ]]; then
  if [[ -n "${DISPLAY:-}${WAYLAND_DISPLAY:-}" ]] || [[ "$(uname -s)" == "Darwin" ]]; then
    case "$(uname -s)" in
      Darwin)  open "$URL" >/dev/null 2>&1 || echo "[start_local] Não consegui abrir o navegador; acesse $URL manualmente." ;;
      Linux)   command -v xdg-open >/dev/null 2>&1 && xdg-open "$URL" >/dev/null 2>&1 \
                || command -v gio      >/dev/null 2>&1 && gio open "$URL" >/dev/null 2>&1 \
                || echo "[start_local] AVISO: instale xdg-utils (xdg-open) para auto-abrir o navegador, ou acesse $URL." ;;
      MINGW*|MSYS*|CYGWIN*) cmd.exe /c start "" "$URL" >/dev/null 2>&1 \
                || echo "[start_local] Não consegui abrir o navegador; acesse $URL manualmente." ;;
      *)       echo "[start_local] OS não reconhecido; acesse $URL manualmente." ;;
    esac
  else
    echo "[start_local] Sem sessão gráfica detectada; acesse $URL manualmente."
  fi
fi
